// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.18.1
// source: animeshon/webpage/v1alpha1/internal.proto

package webpage

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// This is a private internal structure used to store metadata information
// about a specific Page. This structure is never exposed to the public.
type PageEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The page resource id.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// A reference to a parent resource.
	//
	// Types that are assignable to Parent:
	//	*PageEntry_SiteId
	Parent isPageEntry_Parent `protobuf_oneof:"parent"`
	// The document body represented in bytes.
	Document []byte `protobuf:"bytes,3,opt,name=document,proto3" json:"document,omitempty"`
	// When the page entry was created.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
}

func (x *PageEntry) Reset() {
	*x = PageEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_animeshon_webpage_v1alpha1_internal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageEntry) ProtoMessage() {}

func (x *PageEntry) ProtoReflect() protoreflect.Message {
	mi := &file_animeshon_webpage_v1alpha1_internal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageEntry.ProtoReflect.Descriptor instead.
func (*PageEntry) Descriptor() ([]byte, []int) {
	return file_animeshon_webpage_v1alpha1_internal_proto_rawDescGZIP(), []int{0}
}

func (x *PageEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (m *PageEntry) GetParent() isPageEntry_Parent {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (x *PageEntry) GetSiteId() string {
	if x, ok := x.GetParent().(*PageEntry_SiteId); ok {
		return x.SiteId
	}
	return ""
}

func (x *PageEntry) GetDocument() []byte {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *PageEntry) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type isPageEntry_Parent interface {
	isPageEntry_Parent()
}

type PageEntry_SiteId struct {
	// The site resource id. Example: `sites/animeshon-com`.
	SiteId string `protobuf:"bytes,2,opt,name=site_id,json=siteId,proto3,oneof"`
}

func (*PageEntry_SiteId) isPageEntry_Parent() {}

var File_animeshon_webpage_v1alpha1_internal_proto protoreflect.FileDescriptor

var file_animeshon_webpage_v1alpha1_internal_proto_rawDesc = []byte{
	0x0a, 0x29, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x73, 0x68, 0x6f, 0x6e, 0x2f, 0x77, 0x65, 0x62, 0x70,
	0x61, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x61, 0x6e, 0x69,
	0x6d, 0x65, 0x73, 0x68, 0x6f, 0x6e, 0x2e, 0x77, 0x65, 0x62, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x99, 0x01, 0x0a, 0x09, 0x50, 0x61, 0x67,
	0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x07, 0x73, 0x69, 0x74, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x73, 0x69, 0x74, 0x65, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3b, 0x0a,
	0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x70, 0x61,
	0x72, 0x65, 0x6e, 0x74, 0x42, 0x7c, 0x0a, 0x1e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x69, 0x6d,
	0x65, 0x73, 0x68, 0x6f, 0x6e, 0x2e, 0x77, 0x65, 0x62, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x50, 0x01, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x67,
	0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x65, 0x62, 0x70, 0x61,
	0x67, 0x65, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x3b, 0x77, 0x65, 0x62, 0x70,
	0x61, 0x67, 0x65, 0xea, 0x02, 0x1c, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x73, 0x68, 0x6f, 0x6e, 0x3a,
	0x3a, 0x57, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x3a, 0x3a, 0x76, 0x31, 0x41, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_animeshon_webpage_v1alpha1_internal_proto_rawDescOnce sync.Once
	file_animeshon_webpage_v1alpha1_internal_proto_rawDescData = file_animeshon_webpage_v1alpha1_internal_proto_rawDesc
)

func file_animeshon_webpage_v1alpha1_internal_proto_rawDescGZIP() []byte {
	file_animeshon_webpage_v1alpha1_internal_proto_rawDescOnce.Do(func() {
		file_animeshon_webpage_v1alpha1_internal_proto_rawDescData = protoimpl.X.CompressGZIP(file_animeshon_webpage_v1alpha1_internal_proto_rawDescData)
	})
	return file_animeshon_webpage_v1alpha1_internal_proto_rawDescData
}

var file_animeshon_webpage_v1alpha1_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_animeshon_webpage_v1alpha1_internal_proto_goTypes = []interface{}{
	(*PageEntry)(nil),             // 0: animeshon.webpage.v1alpha1.PageEntry
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_animeshon_webpage_v1alpha1_internal_proto_depIdxs = []int32{
	1, // 0: animeshon.webpage.v1alpha1.PageEntry.create_time:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_animeshon_webpage_v1alpha1_internal_proto_init() }
func file_animeshon_webpage_v1alpha1_internal_proto_init() {
	if File_animeshon_webpage_v1alpha1_internal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_animeshon_webpage_v1alpha1_internal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_animeshon_webpage_v1alpha1_internal_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*PageEntry_SiteId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_animeshon_webpage_v1alpha1_internal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_animeshon_webpage_v1alpha1_internal_proto_goTypes,
		DependencyIndexes: file_animeshon_webpage_v1alpha1_internal_proto_depIdxs,
		MessageInfos:      file_animeshon_webpage_v1alpha1_internal_proto_msgTypes,
	}.Build()
	File_animeshon_webpage_v1alpha1_internal_proto = out.File
	file_animeshon_webpage_v1alpha1_internal_proto_rawDesc = nil
	file_animeshon_webpage_v1alpha1_internal_proto_goTypes = nil
	file_animeshon_webpage_v1alpha1_internal_proto_depIdxs = nil
}
